### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by asingh281** [mroreoman/rummy#1]
## later
- [ ] clean up branches
- [ ] make discard menu loop
- [ ] make add to meld nicer
- [ ] implement selectCardFromHand()
- [ ] good computer player
- [ ] gui

https://bicyclecards.com/how-to-play/rummy-rum

**Comment by BUSH224** [comment]
Hi
